# -*- coding: utf-8 -*-
"""T1_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TwvM2ucxRzB_fm9eUNxtMETTmfQ7dQ4

Alunos: Eduardo Traunig, Erick Branquinho Machado
"""

from pathlib import Path

import pandas as pd

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import OneHotEncoder

from sklearn.metrics import classification_report

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

df = pd.read_csv('https://raw.githubusercontent.com/Erick080/T1_ML/refs/heads/main/filtered_thyroid_data.csv')
df.head()

df_encoded = pd.get_dummies(df, columns=[
    'Gender', 'Hx Radiothreapy', 'Adenopathy',
    'Pathology', 'Focality', 'Risk',
    'T', 'N', 'M', 'Stage', 'Response', 'Recurred'
], drop_first=True)

df = df_encoded
df.head()

Y = df['Recurred_Yes']
X = df.drop(columns=['Recurred_Yes'])

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

"""Árvore de Decisão"""

decision_tree = DecisionTreeClassifier()
#param_grid = {
#    'max_depth': [2, 3, 4, 5],
#    'min_samples_split': [2, 4, 6],
#    'min_samples_leaf': [1, 2, 3],
#    'criterion': ['gini', 'entropy']
#}
param_grid = {
    'max_depth': [2, 3, 4, 5],
    'min_samples_split': list(range(2,6)),
    'min_samples_leaf': list(range(1,4)),
    'criterion': ['gini', 'entropy']
}
grid_search = GridSearchCV(decision_tree, param_grid, cv=3, scoring='f1')
grid_search.fit(X_train, Y_train)

print(grid_search.best_params_)
print("F1-Score no GridSearch:")
print(f"{grid_search.best_score_:.4f}")

y_pred = grid_search.predict(X_test)

#print("Relatório de classificação (teste):")
#print(classification_report(Y_test, y_pred))
print('Accuracy:', accuracy_score(Y_test, y_pred))
print('F1:', f1_score(Y_test, y_pred, average='macro'))
print('Precision:', precision_score(Y_test, y_pred, average='macro'))
print('Recall:', recall_score(Y_test, y_pred, average='macro'))

# Plot da Arvore Gerada
best_tree = grid_search.best_estimator_

class_names = [str(cls) for cls in best_tree.classes_]

# Criar a figura
plt.figure(figsize=(24, 12))  # Tamanho ajustável conforme necessário
plot_tree(
    best_tree,
    filled=True,
    feature_names=X_train.columns,      # nomes das colunas codificadas
    class_names=class_names,            # agora as classes estão em string
    rounded=True,
    fontsize=10
)

plt.title("Árvore de Decisão - Melhor Modelo (GridSearchCV)", fontsize=16)
plt.show()

"""Naive Bayes"""

