# -*- coding: utf-8 -*-
"""T1_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TwvM2ucxRzB_fm9eUNxtMETTmfQ7dQ4

Alunos: Eduardo Traunig, Erick Branquinho Machado
"""

from pathlib import Path

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
from sklearn.pipeline import make_pipeline

from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import OneHotEncoder

from sklearn.metrics import classification_report

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

import shap
shap.initjs()

df = pd.read_csv('https://raw.githubusercontent.com/Erick080/T1_ML/refs/heads/main/filtered_thyroid_data.csv')
df.head()

df_encoded = pd.get_dummies(df, columns=[
    'Gender', 'Hx Radiothreapy', 'Adenopathy',
    'Pathology', 'Focality', 'Risk',
    'T', 'N', 'M', 'Stage', 'Response', 'Recurred'
], drop_first=True)

df = df_encoded
df.head()

Y = df['Recurred_Yes']
X = df.drop(columns=['Recurred_Yes'])

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

"""Árvore de Decisão"""

decision_tree = DecisionTreeClassifier()
#param_grid = {
#    'max_depth': [2, 3, 4, 5],
#    'min_samples_split': [2, 4, 6],
#    'min_samples_leaf': [1, 2, 3],
#    'criterion': ['gini', 'entropy']
#}
param_grid = {
    'max_depth': [2, 3, 4, 5],
    'min_samples_split': list(range(2,6)),
    'min_samples_leaf': list(range(1,4)),
    'criterion': ['gini', 'entropy']
}
grid_search = GridSearchCV(decision_tree, param_grid, cv=3, scoring='f1')
grid_search.fit(X_train, Y_train)

print(grid_search.best_params_)
print("F1-Score no GridSearch:")
print(f"{grid_search.best_score_:.4f}")

y_pred = grid_search.predict(X_test)

#print("Relatório de classificação (teste):")
#print(classification_report(Y_test, y_pred))
print('Accuracy:', accuracy_score(Y_test, y_pred))
print('F1:', f1_score(Y_test, y_pred, average='macro'))
print('Precision:', precision_score(Y_test, y_pred, average='macro'))
print('Recall:', recall_score(Y_test, y_pred, average='macro'))

# Plot da Arvore Gerada
best_tree = grid_search.best_estimator_

class_names = [str(cls) for cls in best_tree.classes_]

# Criar a figura
plt.figure(figsize=(24, 12))  # Tamanho ajustável conforme necessário
plot_tree(
    best_tree,
    filled=True,
    feature_names=X_train.columns,      # nomes das colunas codificadas
    class_names=class_names,            # agora as classes estão em string
    rounded=True,
    fontsize=10
)

plt.title("Árvore de Decisão - Melhor Modelo (GridSearchCV)", fontsize=16)
plt.show()

"""Naive Bayes"""



"""KNN

"""

param_grid = {
      'n_neighbors': [7, 8, 9],
      'weights': ['uniform','distance'],
      'leaf_size': [1, 2, 3, 4, 5],
      'p': [1, 2, 3]
  }
# Grid search with cross-validation
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, n_jobs=-1)
grid_search.fit(X_train, Y_train)

print("Best parameters:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)
best_score = grid_search.best_score_

y_pred = grid_search.predict(X_test)

#print("Relatório de classificação (teste):")
#print(classification_report(Y_test, y_pred))
print('Accuracy:', accuracy_score(Y_test, y_pred))
print('F1:', f1_score(Y_test, y_pred, average='macro'))
print('Precision:', precision_score(Y_test, y_pred, average='macro'))
print('Recall:', recall_score(Y_test, y_pred, average='macro'))

"""Configuracao do SHAP para gerar graficos informativos. O primeiro apresenta as features mais importantes na classificacao das instancias do dataset de treino"""

# Função de predição
def f(x):
    return grid_search.predict_proba(x)[:, 1]

# Conversão para float64
X_train_asfloat = X_train.astype(np.float64)
X_test_asfloat = X_test.astype(np.float64)

# Cria o explainer com background mais representativo
explainer = shap.Explainer(f, X_train_asfloat)

# Calcula valores SHAP
shap_values = explainer(X_test_asfloat.iloc[0:1000, :])

# Exibe gráfico de barras com as top features
shap.plots.bar(shap_values)

"""No grafico Beeswarm:
 - Cada ponto representa uma instancia
 - A cor representa o valor da feature, no caso de features booleanas, azul representa false e vermelho true
 - O valor SHAP positivo representa a influencia que a feature teve para classificar como *TRUE* a predicao da recorrencia de cancer de tireoide, e o negativo a predicao da nao recorrencia.
"""

shap.plots.beeswarm(shap_values)